# -*- coding: utf-8 -*-
"""histogram_rgb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cOAAGtBdR0N0MyvaMy5Y-8iXLUISepvc
"""

# Commented out IPython magic to ensure Python compatibility.
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

import cv2
from google.colab.patches import cv2_imshow

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %clear
A= cv2.imread('/content/drive/My Drive/content/col.jpg')
cv2_imshow(A)

print(A)

print(A.shape)

b,g,r = cv2.split(A)

cv2_imshow(g)

def a(channel):
 k=0 
 H= np.zeros((256), dtype=int)  #zero mat 
 print(H) 
 while k < 256:
      H[k] =np.count_nonzero(channel==k)
      k=k+1 
 print(H)                         #eta count
 
 
 Intensity=np.arange(0, 256, 1)

 print (Intensity)

 return Intensity,H


#x,y = a(channel)
 

 

def plot(x,y,c):
  plt.bar(x, y , color= c , width = 0.8)
  plt.xlabel('Intensity')
  plt.ylabel('freq')
  plt.title('Histo')
  plt.show()
 

x,y= a(r)

plot(x,y,'red')


x,y= a(g)

plot(x,y,'green')

x,y = a(b)

plot(x,y,'blue')

